### ISSUE TITLE
센서 등록이 안됩니다.

### ISSUE THREAD

**Issue by lovey25** [miumida/mart_holiday#5]
좋은 툴 만들어주셔서 감사합니다.
제법 오래동안 잘 사용을 했었는데요. 어느 순간 센서정보를 읽어오지 못해서
최근에 HACS로 1.1.0버전으로 다시 설치했습니다.
그리고
센서 구성은 다음과 같이 했는데요.
--(/config/devices/sensor.yaml)----------------------
```
- platform: mart_holiday
  marts:
    - mart_kind: 'g'
      name: 'GS그린워크점'
      mart_code: 11239
    - mart_kind: 'c'
      name: '코스트코송도점'
      mart_code: '12'
    - mart_kind: 'h'
      name: '홈플러스송도점'
      mart_code: '0124'
    - mart_kind: 'e'
      name: '노브랜드송도점'
      mart_code: '4089'
      area: 'C'    
    - mart_kind: 'l'
      name: '롯데마트송도점'
      mart_code: '0100235'
```
-------------------------------------------------------

구성 내용 유효성 검사를 하면 아래와 같은 오류가 발생합니다.

Invalid config for [sensor.mart_holiday]: [marts] is an invalid option for [sensor.mart_holiday]. Check: sensor.mart_holiday->marts. (See ?, line ?).

뭐가 문제인지 모르겠습니다.
